Repository googleapis/nodejs-bigquery-storage, pull requests merged in 2020-06, with the labels that each got.

#67 chore: update protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: none

#70 feat(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v1/big_query_read_client.ts
  src/v1beta1/big_query_storage_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#73 fix: handle fallback option properly
  .kokoro/populate-secrets.sh
  src/v1/big_query_read_client.ts
  src/v1beta1/big_query_storage_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#75 feat: promote library to GA
  .github/ISSUE_TEMPLATE/bug_report.md
  .repo-metadata.json
  README.md
  synth.metadata
Labels: cla: yes

#77 chore: add blunderbuss config
  .github/blunderbuss.yaml
Labels: cla: yes

#80 build: add config .gitattributes
  .gitattributes
  .kokoro/.gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
