Repository googleapis/nodejs-bigquery-storage, pull requests merged in 2020-11, with the labels that each got.

#125 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full

#126 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/big_query_read_client.ts
  src/v1beta1/big_query_storage_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: bigquerystorage, automerge, cla: yes

#129 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/big_query_read_client.ts
  src/v1beta1/big_query_storage_client.ts
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: none

#131 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full
