Repository googleapis/nodejs-bigquery-storage, pull requests merged in 2020-05, with the labels that each got.

#63 fix: regen protos and tests
  synth.metadata
  test/gapic_big_query_read_v1.ts
  test/gapic_big_query_storage_v1beta1.ts
Labels: automerge, cla: yes

#64 feat: additional type annotation
  protos/google/cloud/bigquery/storage/v1beta1/arrow.proto
  protos/google/cloud/bigquery/storage/v1beta1/avro.proto
  protos/google/cloud/bigquery/storage/v1beta1/read_options.proto
  protos/google/cloud/bigquery/storage/v1beta1/storage.proto
  protos/google/cloud/bigquery/storage/v1beta1/table_reference.proto
  protos/protos.json
  src/v1beta1/big_query_storage_client.ts
  synth.metadata
Labels: automerge, cla: yes, context: none

#66 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
