Repository googleapis/nodejs-bigquery-storage, pull requests merged in 2020-10, with the labels that each got.

#112 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#113 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: api: bigquerystorage, automerge: exact, cla: yes, context: full

#119 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#118 docs(samples): update quickstart to use v1 client
  samples/quickstart.js
Labels: api: bigquerystorage, cla: yes, samples

#120 docs: update sample on README to latest
  README.md
  synth.metadata
Labels: cla: yes, context: none

#121 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#124 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full
